version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - 5577:5577
    environment:
      SLOW_QUERIES_LOGGING: "true"
      SLOW_QUERIES_LOGGING_THRESHOLD: "50"
      PRISMA_CONFIG: |
        port: 5577
        databases:
          default:
            connector: mysql
            host: mysql-container
            port: 3306
            user: root
            password: o49zcMdvmBKqqcMTIf91yfSayWe5RLT3FRrFtuZFVzTbzwT8BQZXVGXhq0b8BSZ4
            migrations: true
  mysql-container:
    image: mysql:5.7
    restart: always
    ports:
      - 3303:3306
    environment:
      MYSQL_ROOT_PASSWORD: o49zcMdvmBKqqcMTIf91yfSayWe5RLT3FRrFtuZFVzTbzwT8BQZXVGXhq0b8BSZ4
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    restart: always